### ISSUE TITLE
misspelled

### ISSUE THREAD

**Issue by sp-7indigo** [wso2/carbon-identity-framework#1614]
https://github.com/wso2/carbon-identity-framework/blob/0a48843d4a597ead9a5594f18c65ca479abcdad4/components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-edit.jsp#L3219

sould be "federation.hub.identity.provider" (?)

**Comment by deshankoswatte** [comment]
Hi @sp-7indigo,

This is fixed in, [https://github.com/wso2/carbon-identity-framework/blob/39abb9a2fac016c03f8ea783a88ef1e24499639b/components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-edit.jsp#L3178](https://github.com/wso2/carbon-identity-framework/blob/39abb9a2fac016c03f8ea783a88ef1e24499639b/components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-edit.jsp#L3178) 

Hence closing this issue.
